<x-layouts.app :narrow="true" :meta="$meta"><div class="mx-auto w-full max-w-4xl">@include('carpool.nav')
@include('carpool.partials.offer-context')
<div data-ride-chat data-url="{{ route('carpool.chat',$chat_id) }}" data-send="{{ route('carpool.chat.action',[$chat_id,'send']) }}" data-preferences="{{ route('carpool.chat.action',[$chat_id,'preferences']) }}" data-readonly="{{ __('carpool.chat_readonly') }}" data-error="{{ __('carpool.errors.generic') }}">
<h2 class="text-section">{{ $ride['is_driver'] ? $ride['requester']['name'] : $offer['driver']['name'] }}</h2><p class="mt-3 text-sm text-ink-muted">{{ __('carpool.chat_context') }}</p>
<button type="button" data-chat-older class="my-5 inline-flex min-h-12 items-center underline">{{ __('carpool.older') }}</button>
<div data-chat-messages role="log" aria-live="polite" aria-relevant="additions" class="my-4 max-h-[55dvh] space-y-4 overflow-y-auto p-1">@foreach($messages as $message)<article data-message-id="{{ $message['id'] }}" class="max-w-[85%] border border-line p-4 {{ $message['mine'] ? 'ml-auto bg-surface' : '' }}"><p class="whitespace-pre-wrap break-words">{{ $message['body'] }}</p><time class="mt-2 block text-xs text-ink-muted">{{ \Carbon\CarbonImmutable::parse($message['created_at'])->setTimezone('Europe/Rome')->format('d/m H:i') }}</time></article>@endforeach</div>
<p data-chat-error role="alert" class="my-4 text-sm"></p>
@if($writable)<form data-chat-send method="post" action="{{ route('carpool.chat.action',[$chat_id,'send']) }}" class="sticky bottom-20 border border-line bg-canvas p-4">@include('carpool.partials.key')<label class="block text-sm font-semibold">{{ __('carpool.message') }}<textarea required name="body" maxlength="2000" rows="3" class="mt-2 w-full border border-line bg-canvas p-3"></textarea></label><x-button type="submit" class="mt-3">{{ __('carpool.send') }}</x-button></form>@else<p class="border border-line p-5">{{ __('carpool.chat_readonly') }}</p>@endif
<form action="{{ route('carpool.chat.action',[$chat_id,'preferences']) }}" method="post" class="my-6 flex flex-wrap items-center gap-4">@csrf<input type="hidden" name="archived" value="0"><label class="flex min-h-12 items-center gap-3"><input type="checkbox" name="archived" value="1" @checked($archived)>{{ __('carpool.archive_chat') }}</label><input type="hidden" name="muted" value="0"><label class="flex min-h-12 items-center gap-3"><input type="checkbox" name="muted" value="1" @checked($muted)>{{ __('carpool.muted') }}</label><x-button variant="secondary" type="submit">{{ __('carpool.save') }}</x-button></form>
</div>
@include('carpool.partials.report')
</div></x-layouts.app>
