<?php

// Local catalog: Provincia di Padova (101 municipalities), Comune di Padova (rioni).
// Sources and upgrade policy: docs/SCELTA-RAPIDA.md. No geocoding guesses for legacy venues.
return [
    'padova' => [
        'municipalities' => explode('|', "Padova|Abano Terme|Agna|Albignasego|Anguillara Veneta|Arquà Petrarca|Arre|Arzergrande|Bagnoli di Sopra|Baone|Barbona|Battaglia Terme|Boara Pisani|Borgo Veneto|Borgoricco|Bovolenta|Brugine|Cadoneghe|Campodarsego|Campodoro|Camposampiero|Campo San Martino|Candiana|Carmignano di Brenta|Cartura|Casale di Scodosia|Casalserugo|Castelbaldo|Cervarese Santa Croce|Cinto Euganeo|Cittadella|Codevigo|Conselve|Correzzola|Curtarolo|Due Carrare|Este|Fontaniva|Galliera Veneta|Galzignano Terme|Gazzo|Grantorto|Granze|Legnaro|Limena|Loreggia|Lozzo Atestino|Maserà di Padova|Masi|Massanzago|Megliadino San Vitale|Merlara|Mestrino|Monselice|Montagnana|Montegrotto Terme|Noventa Padovana|Ospedaletto Euganeo|Pernumia|Piacenza d'Adige|Piazzola sul Brenta|Piombino Dese|Piove di Sacco|Polverara|Ponso|Pontelongo|Ponte San Nicolò|Pozzonovo|Rovolon|Rubano|Saccolongo|San Giorgio delle Pertiche|San Giorgio in Bosco|San Martino di Lupari|San Pietro in Gu|San Pietro Viminario|Santa Caterina d'Este|Santa Giustina in Colle|Sant'Angelo di Piove di Sacco|Sant'Elena|Sant'Urbano|Saonara|Selvazzano Dentro|Solesino|Stanghella|Teolo|Terrassa Padovana|Tombolo|Torreglia|Trebaseleghe|Tribano|Urbana|Veggiano|Vescovana|Vigodarzere|Vigonza|Villa del Conte|Villa Estense|Villafranca Padovana|Villanova di Camposampiero|Vo'"),
        'districts' => explode('|', "Centro|Altichiero|Arcella|Armistizio|Bassanello|Brentelle|Brusegana|Camin|Cave|Chiesanuova|Città Giardino|Crocefisso|Fiera|Forcellini|Granze|Guizza|Isola di Terranegra|Madonna Pellegrina|Mandria|Montà|Mortise|Palestro|Paltana|Piazze|Ponte di Brenta|Ponterotto|Pontevigodarzere|Porta Trento|Portello|Prato della Valle|Sacra Famiglia|Sacro Cuore|Salboro|San Bellino|San Carlo|San Giuseppe|San Lazzaro|San Paolo|Santa Croce|Santa Rita|Sant'Ignazio|Sant'Osvaldo|Santo|Savonarola|Stanga|Stazione|Terranegra|Torre|Voltabarozzo|Voltabrusegana|Zona Industriale"),
    ],
];
