<?php

// Keep the two clients on the same reviewed Italian product copy.
$root = dirname(__DIR__);
$flatten = function (array $items, string $prefix = '') use (&$flatten): array {
    $result = [];
    foreach ($items as $key => $value) {
        $path = $prefix.$key;
        if (is_array($value)) {
            $result += $flatten($value, $path.'.');
        } elseif (is_string($value)) {
            $result[$path] = $value;
        }
    }

    return $result;
};
$items = $flatten(require $root.'/lang/it/carpool.php');
$xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<resources>\n";
$map = [];
foreach ($items as $key => $value) {
    $id = 'cp_'.strtolower(str_replace('.', '_', $key));
    $xml .= '    <string name="'.$id.'" formatted="false">'.htmlspecialchars(str_replace(["'", '"'], ["\\'", '\\"'], $value), ENT_XML1)."</string>\n";
    $map[] = '    "'.$key.'" to R.string.'.$id;
}
file_put_contents($root.'/android/app/src/main/res/values/carpool.xml', $xml."</resources>\n");
file_put_contents($root.'/android/app/src/main/java/it/fabiodalez/incitta/ui/CarpoolStrings.kt', "// Generated by scripts/sync-carpool-android-strings.php\npackage it.fabiodalez.incitta.ui\n\nimport androidx.compose.runtime.Composable\nimport androidx.compose.ui.res.stringResource\nimport it.fabiodalez.incitta.R\n\nprivate val carpoolStrings = mapOf(\n".implode(",\n", $map)."\n)\n@Composable\ninternal fun cpText(key: String, vararg values: Pair<String, Any>): String {\n    var text = stringResource(requireNotNull(carpoolStrings[key]))\n    values.forEach { (name, value) -> text = text.replace(\":\$name\", value.toString()) }\n    return text\n}\n");
