<div class="grid gap-5 sm:grid-cols-2">
    <label class="block space-y-2"><span class="text-sm font-semibold">{{ __('carpool.zone') }}</span><input required name="zone" maxlength="120" value="{{ old('zone', $offer['zone'] ?? '') }}" class="min-h-12 w-full border border-line bg-canvas px-4"></label>
    <label class="block space-y-2"><span class="text-sm font-semibold">{{ __('carpool.departure') }}</span><input required type="datetime-local" name="departure_at" value="{{ old('departure_at', $offer['departure_local'] ?? '') }}" class="min-h-12 w-full border border-line bg-canvas px-4"></label>
    <label class="block space-y-2"><span class="text-sm font-semibold">{{ __('carpool.seats') }}</span><input required type="number" name="capacity" min="1" max="8" value="{{ old('capacity', $offer['capacity'] ?? 1) }}" class="min-h-12 w-full border border-line bg-canvas px-4"></label>
    <label class="block space-y-2"><span class="text-sm font-semibold">{{ __('carpool.accessibility') }}</span><select name="accessibility" class="min-h-12 w-full border border-line bg-canvas px-4">@foreach(\App\Enums\RideAccessibility::cases() as $option)<option value="{{ $option->value }}" @selected(old('accessibility', $offer['accessibility'] ?? 'not_specified') === $option->value)>{{ $option->label() }}</option>@endforeach</select></label>
</div>
<p class="text-sm text-ink-muted">{{ __('carpool.accessibility_disclaimer') }}</p>
<label class="block space-y-2"><span class="text-sm font-semibold">{{ __('carpool.accessibility_note') }}</span><input name="accessibility_note" maxlength="300" value="{{ old('accessibility_note', $offer['accessibility_note'] ?? '') }}" class="min-h-12 w-full border border-line bg-canvas px-4"></label>
<details class="border-y border-line py-4"><summary class="min-h-10 cursor-pointer font-semibold">{{ __('carpool.stops') }}</summary><div class="mt-3 grid gap-3">@for($i=0;$i<3;$i++)<label class="block space-y-2"><span class="text-sm">{{ __('carpool.stop') }} {{ $i+1 }}</span><input name="stops[]" maxlength="120" value="{{ old('stops.'.$i, $offer['stops'][$i] ?? '') }}" class="min-h-12 w-full border border-line bg-canvas px-4"></label>@endfor</div></details>
<label class="block space-y-2"><span class="text-sm font-semibold">{{ __('carpool.note') }}</span><textarea name="note" maxlength="500" rows="3" class="w-full border border-line bg-canvas p-4">{{ old('note', $offer['note'] ?? '') }}</textarea></label>
